"""clinical dictionary: self-populating

Revision ID: 0cb18f7bcf7e
Revises: 53b20cdffe2b
Create Date: 2026-10-04 10:49:07.073042+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "0cb18f7bcf7e"
down_revision: str | None = "53b20cdffe2b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "canonical_tests",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("display_name", sa.String(length=160), nullable=False),
        sa.Column("panel", sa.String(length=80), nullable=True),
        sa.Column("canonical_unit", sa.String(length=40), nullable=True),
        sa.Column("sidedness", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("proposed_by", sa.String(length=40), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_canonical_tests")),
    )
    op.create_table(
        "unmapped_test_names",
        sa.Column("key", sa.String(length=200), nullable=False),
        sa.Column("raw_example", sa.Text(), nullable=False),
        sa.Column("occurrences", sa.Integer(), nullable=False),
        sa.Column(
            "first_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("resolved_to", sa.String(length=64), nullable=True),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_unmapped_test_names")),
    )
    op.create_index("ix_unmapped_occurrences", "unmapped_test_names", ["occurrences"], unique=False)
    op.create_table(
        "critical_values",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("canonical_test_id", sa.String(length=64), nullable=False),
        sa.Column("comparator", sa.String(length=4), nullable=False),
        sa.Column("threshold", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("unit", sa.String(length=40), nullable=False),
        sa.Column("message_template", sa.Text(), nullable=False),
        sa.Column("source", sa.String(length=160), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("reviewed_by", sa.String(length=80), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "comparator in ('lt','gt')", name=op.f("ck_critical_values_comparator_known")
        ),
        sa.ForeignKeyConstraint(
            ["canonical_test_id"],
            ["canonical_tests.id"],
            name=op.f("fk_critical_values_canonical_test_id_canonical_tests"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_critical_values")),
    )
    op.create_index(
        "ix_critical_values_test", "critical_values", ["canonical_test_id", "status"], unique=False
    )
    op.create_table(
        "test_aliases",
        sa.Column("key", sa.String(length=200), nullable=False),
        sa.Column("canonical_test_id", sa.String(length=64), nullable=False),
        sa.Column("raw_example", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["canonical_test_id"],
            ["canonical_tests.id"],
            name=op.f("fk_test_aliases_canonical_test_id_canonical_tests"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_test_aliases")),
    )
    op.create_index(
        "ix_test_aliases_canonical", "test_aliases", ["canonical_test_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_test_aliases_canonical", table_name="test_aliases")
    op.drop_table("test_aliases")
    op.drop_index("ix_critical_values_test", table_name="critical_values")
    op.drop_table("critical_values")
    op.drop_index("ix_unmapped_occurrences", table_name="unmapped_test_names")
    op.drop_table("unmapped_test_names")
    op.drop_table("canonical_tests")
    # ### end Alembic commands ###
