"""unit conversions, derived from reports

Revision ID: e9a044ca5e03
Revises: 0cb18f7bcf7e
Create Date: 2026-10-04 10:57:35.611614+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "e9a044ca5e03"
down_revision: str | None = "0cb18f7bcf7e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "unit_conversions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("canonical_test_id", sa.String(length=64), nullable=False),
        sa.Column("from_unit", sa.String(length=40), nullable=False),
        sa.Column("to_unit", sa.String(length=40), nullable=False),
        sa.Column("factor", sa.Numeric(precision=30, scale=12), nullable=False),
        sa.Column("agreement", sa.Numeric(precision=10, scale=6), nullable=True),
        sa.Column("derived_from", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["canonical_test_id"],
            ["canonical_tests.id"],
            name=op.f("fk_unit_conversions_canonical_test_id_canonical_tests"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_unit_conversions")),
        sa.UniqueConstraint(
            "canonical_test_id", "from_unit", "to_unit", name="uq_unit_conversions_test_units"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("unit_conversions")
    # ### end Alembic commands ###
